eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8763
spring:
  application:
    name: train-server
  rabbitmq:
    host: 192.168.253.4
    port: 5672
    password: admin
    username: admin
    virtual-host: /
    listener:
      auto-startup: true
