eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8763
spring:
  application:
    name: train-server
  rabbitmq:
    host: 47.112.204.23
    port: 5672
    password: guest
    username: guest
    virtual-host: /
    listener:
      auto-startup: true
